// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :one

INSERT INTO email_verifications (
    user_id,
    token_hash,
    email,
    expires_at
) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, email, expires_at, used_at, created_at
`

type CreateEmailVerificationParams struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	Email     string             `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// ── Email verifications ───────────────────────────────────────────────────────
func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification,
		arg.UserID,
		arg.TokenHash,
		arg.Email,
		arg.ExpiresAt,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one

INSERT INTO password_resets (
    user_id,
    token_hash,
    expires_at
) VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// ── Password resets ───────────────────────────────────────────────────────────
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    expires_at
) VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// ── Refresh tokens ────────────────────────────────────────────────────────────
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets
WHERE expires_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResets)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW() - INTERVAL '7 days'
`

// Maintenance query — run nightly.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT id, user_id, token_hash, email, expires_at, used_at, created_at FROM email_verifications
WHERE token_hash = $1
  AND used_at    IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetEmailVerification(ctx context.Context, tokenHash string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerification, tokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Email,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordReset = `-- name: GetPasswordReset :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_resets
WHERE token_hash = $1
  AND used_at    IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetPasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordReset, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked, created_at FROM refresh_tokens
WHERE token_hash = $1
  AND revoked     = FALSE
  AND expires_at > NOW()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications SET
    used_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, tokenHash)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets SET
    used_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, tokenHash)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET
    revoked = TRUE
WHERE user_id = $1
  AND revoked = FALSE
`

// Called on password change or explicit sign-out-all-devices.
func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET
    revoked = TRUE
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
