// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: check_ins.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCheckIns = `-- name: CountCheckIns :one
SELECT COUNT(*) FROM check_ins
WHERE user_id = $1
`

func (q *Queries) CountCheckIns(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckIns, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckInsInRange = `-- name: CountCheckInsInRange :one
SELECT COUNT(*) FROM check_ins
WHERE user_id = $1
  AND checked_in_date BETWEEN $2 AND $3
`

type CountCheckInsInRangeParams struct {
	UserID          uuid.UUID   `db:"user_id" json:"user_id"`
	CheckedInDate   pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
	CheckedInDate_2 pgtype.Date `db:"checked_in_date_2" json:"checked_in_date_2"`
}

func (q *Queries) CountCheckInsInRange(ctx context.Context, arg CountCheckInsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckInsInRange, arg.UserID, arg.CheckedInDate, arg.CheckedInDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO check_ins (
    user_id,
    checked_in_date,
    stress,
    note,
    score,
    role_snapshot,
    sleep_snapshot,
    meeting_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms
`

type CreateCheckInParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	CheckedInDate pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
	Stress        int16       `db:"stress" json:"stress"`
	Note          pgtype.Text `db:"note" json:"note"`
	Score         int16       `db:"score" json:"score"`
	RoleSnapshot  string      `db:"role_snapshot" json:"role_snapshot"`
	SleepSnapshot int16       `db:"sleep_snapshot" json:"sleep_snapshot"`
	MeetingCount  pgtype.Int2 `db:"meeting_count" json:"meeting_count"`
}

func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, createCheckIn,
		arg.UserID,
		arg.CheckedInDate,
		arg.Stress,
		arg.Note,
		arg.Score,
		arg.RoleSnapshot,
		arg.SleepSnapshot,
		arg.MeetingCount,
	)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckedInDate,
		&i.Stress,
		&i.Note,
		&i.Score,
		&i.RoleSnapshot,
		&i.SleepSnapshot,
		&i.MeetingCount,
		&i.AiRecoveryPlan,
		&i.AiGeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnergyLevel,
		&i.FocusQuality,
		&i.HoursWorked,
		&i.PhysicalSymptoms,
	)
	return i, err
}

const exportUserCheckIns = `-- name: ExportUserCheckIns :many
SELECT
    id,
    checked_in_date,
    stress,
    note,
    score,
    role_snapshot,
    sleep_snapshot,
    created_at
FROM check_ins
WHERE user_id = $1
ORDER BY checked_in_date ASC
`

type ExportUserCheckInsRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CheckedInDate pgtype.Date        `db:"checked_in_date" json:"checked_in_date"`
	Stress        int16              `db:"stress" json:"stress"`
	Note          pgtype.Text        `db:"note" json:"note"`
	Score         int16              `db:"score" json:"score"`
	RoleSnapshot  string             `db:"role_snapshot" json:"role_snapshot"`
	SleepSnapshot int16              `db:"sleep_snapshot" json:"sleep_snapshot"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Full export for GDPR / POPIA data portability.
func (q *Queries) ExportUserCheckIns(ctx context.Context, userID uuid.UUID) ([]ExportUserCheckInsRow, error) {
	rows, err := q.db.Query(ctx, exportUserCheckIns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportUserCheckInsRow{}
	for rows.Next() {
		var i ExportUserCheckInsRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckedInDate,
			&i.Stress,
			&i.Note,
			&i.Score,
			&i.RoleSnapshot,
			&i.SleepSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckInByID = `-- name: GetCheckInByID :one
SELECT id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms FROM check_ins
WHERE id = $1
  AND user_id = $2
`

type GetCheckInByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCheckInByID(ctx context.Context, arg GetCheckInByIDParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckInByID, arg.ID, arg.UserID)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckedInDate,
		&i.Stress,
		&i.Note,
		&i.Score,
		&i.RoleSnapshot,
		&i.SleepSnapshot,
		&i.MeetingCount,
		&i.AiRecoveryPlan,
		&i.AiGeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnergyLevel,
		&i.FocusQuality,
		&i.HoursWorked,
		&i.PhysicalSymptoms,
	)
	return i, err
}

const getCheckInStreak = `-- name: GetCheckInStreak :one
WITH RECURSIVE streak AS (
    SELECT
        checked_in_date,
        1 AS n
    FROM check_ins
    WHERE check_ins.user_id = $1                     -- qualified
      AND checked_in_date = (
          SELECT MAX(checked_in_date)
          FROM check_ins
          WHERE check_ins.user_id = $1               -- qualified
            AND checked_in_date >= CURRENT_DATE - 1
      )
    UNION ALL
    SELECT
        ci.checked_in_date,
        s.n + 1
    FROM check_ins ci
    JOIN streak s ON ci.checked_in_date = s.checked_in_date - INTERVAL '1 day'
    WHERE ci.user_id = $1                             -- already qualified
)
SELECT COALESCE(MAX(n), 0)::INT AS streak
FROM streak
`

// Counts consecutive days with a check-in ending today (or yesterday if
// today has no check-in yet). Returns 0 when no streak exists.
func (q *Queries) GetCheckInStreak(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCheckInStreak, userID)
	var streak int32
	err := row.Scan(&streak)
	return streak, err
}

const getConsecutiveDangerDays = `-- name: GetConsecutiveDangerDays :one
WITH RECURSIVE danger AS (
    SELECT
        checked_in_date,
        score,
        1 AS n
    FROM check_ins
    WHERE check_ins.user_id = $1                     -- qualified
      AND checked_in_date = CURRENT_DATE - 1
      AND score > 65
    UNION ALL
    SELECT
        ci.checked_in_date,
        ci.score,
        d.n + 1
    FROM check_ins ci
    JOIN danger d ON ci.checked_in_date = d.checked_in_date - INTERVAL '1 day'
    WHERE ci.user_id = $1                             -- already qualified
      AND ci.score > 65
)
SELECT COALESCE(MAX(n), 0)::INT AS consecutive_danger_days
FROM danger
`

// Counts consecutive past days (not including today) where score > 65.
func (q *Queries) GetConsecutiveDangerDays(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getConsecutiveDangerDays, userID)
	var consecutive_danger_days int32
	err := row.Scan(&consecutive_danger_days)
	return consecutive_danger_days, err
}

const getMonthlyAverageScore = `-- name: GetMonthlyAverageScore :one
SELECT
    ROUND(AVG(score))::INT AS avg_score,
    COUNT(*)::INT           AS entry_count
FROM check_ins
WHERE user_id   = $1
  AND EXTRACT(YEAR  FROM checked_in_date) = $2
  AND EXTRACT(MONTH FROM checked_in_date) = $3
`

type GetMonthlyAverageScoreParams struct {
	UserID          uuid.UUID   `db:"user_id" json:"user_id"`
	CheckedInDate   pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
	CheckedInDate_2 pgtype.Date `db:"checked_in_date_2" json:"checked_in_date_2"`
}

type GetMonthlyAverageScoreRow struct {
	AvgScore   int32 `db:"avg_score" json:"avg_score"`
	EntryCount int32 `db:"entry_count" json:"entry_count"`
}

// Returns the average score for a given calendar month (year + month number).
func (q *Queries) GetMonthlyAverageScore(ctx context.Context, arg GetMonthlyAverageScoreParams) (GetMonthlyAverageScoreRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyAverageScore, arg.UserID, arg.CheckedInDate, arg.CheckedInDate_2)
	var i GetMonthlyAverageScoreRow
	err := row.Scan(&i.AvgScore, &i.EntryCount)
	return i, err
}

const getScoreTrendVs7DaysAgo = `-- name: GetScoreTrendVs7DaysAgo :one
SELECT
    today.score - week_ago.score AS delta
FROM
    (SELECT score FROM check_ins WHERE check_ins.user_id = $1 AND check_ins.checked_in_date = $2) AS today,
    (SELECT score FROM check_ins WHERE check_ins.user_id = $1 AND check_ins.checked_in_date = $2 - 7) AS week_ago
`

type GetScoreTrendVs7DaysAgoParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	CheckedInDate pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
}

// Returns the score delta between today and 7 days ago.
func (q *Queries) GetScoreTrendVs7DaysAgo(ctx context.Context, arg GetScoreTrendVs7DaysAgoParams) (int32, error) {
	row := q.db.QueryRow(ctx, getScoreTrendVs7DaysAgo, arg.UserID, arg.CheckedInDate)
	var delta int32
	err := row.Scan(&delta)
	return delta, err
}

const getTodayCheckIn = `-- name: GetTodayCheckIn :one
SELECT id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms FROM check_ins
WHERE user_id = $1
  AND checked_in_date = $2
`

type GetTodayCheckInParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	CheckedInDate pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
}

func (q *Queries) GetTodayCheckIn(ctx context.Context, arg GetTodayCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getTodayCheckIn, arg.UserID, arg.CheckedInDate)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckedInDate,
		&i.Stress,
		&i.Note,
		&i.Score,
		&i.RoleSnapshot,
		&i.SleepSnapshot,
		&i.MeetingCount,
		&i.AiRecoveryPlan,
		&i.AiGeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnergyLevel,
		&i.FocusQuality,
		&i.HoursWorked,
		&i.PhysicalSymptoms,
	)
	return i, err
}

const getYesterdayCheckIn = `-- name: GetYesterdayCheckIn :one
SELECT id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms FROM check_ins
WHERE user_id = $1
  AND checked_in_date = $2 - INTERVAL '1 day'
`

type GetYesterdayCheckInParams struct {
	UserID  uuid.UUID   `db:"user_id" json:"user_id"`
	Column2 interface{} `db:"column_2" json:"column_2"`
}

func (q *Queries) GetYesterdayCheckIn(ctx context.Context, arg GetYesterdayCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getYesterdayCheckIn, arg.UserID, arg.Column2)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckedInDate,
		&i.Stress,
		&i.Note,
		&i.Score,
		&i.RoleSnapshot,
		&i.SleepSnapshot,
		&i.MeetingCount,
		&i.AiRecoveryPlan,
		&i.AiGeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnergyLevel,
		&i.FocusQuality,
		&i.HoursWorked,
		&i.PhysicalSymptoms,
	)
	return i, err
}

const listCheckIns = `-- name: ListCheckIns :many
SELECT id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms FROM check_ins
WHERE user_id = $1
ORDER BY checked_in_date DESC
LIMIT $2
OFFSET $3
`

type ListCheckInsParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

// Paginated history, newest first. Used by the History page.
func (q *Queries) ListCheckIns(ctx context.Context, arg ListCheckInsParams) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckIns, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckIn{}
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CheckedInDate,
			&i.Stress,
			&i.Note,
			&i.Score,
			&i.RoleSnapshot,
			&i.SleepSnapshot,
			&i.MeetingCount,
			&i.AiRecoveryPlan,
			&i.AiGeneratedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnergyLevel,
			&i.FocusQuality,
			&i.HoursWorked,
			&i.PhysicalSymptoms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckInsForDayOfWeek = `-- name: ListCheckInsForDayOfWeek :many
SELECT
    checked_in_date,
    stress,
    score
FROM check_ins
WHERE user_id = $1
  AND EXTRACT(DOW FROM checked_in_date) = $2
ORDER BY checked_in_date DESC
`

type ListCheckInsForDayOfWeekParams struct {
	UserID        uuid.UUID   `db:"user_id" json:"user_id"`
	CheckedInDate pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
}

type ListCheckInsForDayOfWeekRow struct {
	CheckedInDate pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
	Stress        int16       `db:"stress" json:"stress"`
	Score         int16       `db:"score" json:"score"`
}

// Returns all check-ins for a specific day of week (0=Sun … 6=Sat).
// Used by the earned-pattern-insight DOW analysis.
func (q *Queries) ListCheckInsForDayOfWeek(ctx context.Context, arg ListCheckInsForDayOfWeekParams) ([]ListCheckInsForDayOfWeekRow, error) {
	rows, err := q.db.Query(ctx, listCheckInsForDayOfWeek, arg.UserID, arg.CheckedInDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckInsForDayOfWeekRow{}
	for rows.Next() {
		var i ListCheckInsForDayOfWeekRow
		if err := rows.Scan(&i.CheckedInDate, &i.Stress, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckInsInRange = `-- name: ListCheckInsInRange :many
SELECT id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms FROM check_ins
WHERE user_id = $1
  AND checked_in_date BETWEEN $2 AND $3
ORDER BY checked_in_date ASC
`

type ListCheckInsInRangeParams struct {
	UserID          uuid.UUID   `db:"user_id" json:"user_id"`
	CheckedInDate   pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
	CheckedInDate_2 pgtype.Date `db:"checked_in_date_2" json:"checked_in_date_2"`
}

// Used by pattern detection, arc computation, and weekly debrief.
func (q *Queries) ListCheckInsInRange(ctx context.Context, arg ListCheckInsInRangeParams) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckInsInRange, arg.UserID, arg.CheckedInDate, arg.CheckedInDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckIn{}
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CheckedInDate,
			&i.Stress,
			&i.Note,
			&i.Score,
			&i.RoleSnapshot,
			&i.SleepSnapshot,
			&i.MeetingCount,
			&i.AiRecoveryPlan,
			&i.AiGeneratedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnergyLevel,
			&i.FocusQuality,
			&i.HoursWorked,
			&i.PhysicalSymptoms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckInsNeedingAIPlan = `-- name: ListCheckInsNeedingAIPlan :many
SELECT id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms FROM check_ins
WHERE ai_recovery_plan IS NULL
  AND note IS NOT NULL
  AND stress >= 4
  AND created_at >= NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC
LIMIT 50
`

// Used by background worker to generate AI plans for high-stress check-ins
// that were submitted before the AI service was available, or where it
// timed out.
func (q *Queries) ListCheckInsNeedingAIPlan(ctx context.Context) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckInsNeedingAIPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckIn{}
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CheckedInDate,
			&i.Stress,
			&i.Note,
			&i.Score,
			&i.RoleSnapshot,
			&i.SleepSnapshot,
			&i.MeetingCount,
			&i.AiRecoveryPlan,
			&i.AiGeneratedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnergyLevel,
			&i.FocusQuality,
			&i.HoursWorked,
			&i.PhysicalSymptoms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCheckIns = `-- name: ListRecentCheckIns :many
SELECT
    checked_in_date,
    stress,
    score,
    note,
    energy_level,
    focus_quality,
    hours_worked,
    physical_symptoms
FROM check_ins
WHERE user_id = $1
  AND checked_in_date >= CURRENT_DATE - $2::INT
ORDER BY checked_in_date DESC
`

type ListRecentCheckInsParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Column2 int32     `db:"column_2" json:"column_2"`
}

type ListRecentCheckInsRow struct {
	CheckedInDate    pgtype.Date    `db:"checked_in_date" json:"checked_in_date"`
	Stress           int16          `db:"stress" json:"stress"`
	Score            int16          `db:"score" json:"score"`
	Note             pgtype.Text    `db:"note" json:"note"`
	EnergyLevel      pgtype.Int2    `db:"energy_level" json:"energy_level"`
	FocusQuality     pgtype.Int2    `db:"focus_quality" json:"focus_quality"`
	HoursWorked      pgtype.Numeric `db:"hours_worked" json:"hours_worked"`
	PhysicalSymptoms []string       `db:"physical_symptoms" json:"physical_symptoms"`
}

// Last N days of check-ins for the score engine's recentStresses input and AI history compression.
func (q *Queries) ListRecentCheckIns(ctx context.Context, arg ListRecentCheckInsParams) ([]ListRecentCheckInsRow, error) {
	rows, err := q.db.Query(ctx, listRecentCheckIns, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentCheckInsRow{}
	for rows.Next() {
		var i ListRecentCheckInsRow
		if err := rows.Scan(
			&i.CheckedInDate,
			&i.Stress,
			&i.Score,
			&i.Note,
			&i.EnergyLevel,
			&i.FocusQuality,
			&i.HoursWorked,
			&i.PhysicalSymptoms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAIRecoveryPlan = `-- name: SetAIRecoveryPlan :exec
UPDATE check_ins SET
    ai_recovery_plan = $3,
    ai_generated_at  = NOW()
WHERE id      = $1
  AND user_id = $2
`

type SetAIRecoveryPlanParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	AiRecoveryPlan []byte    `db:"ai_recovery_plan" json:"ai_recovery_plan"`
}

func (q *Queries) SetAIRecoveryPlan(ctx context.Context, arg SetAIRecoveryPlanParams) error {
	_, err := q.db.Exec(ctx, setAIRecoveryPlan, arg.ID, arg.UserID, arg.AiRecoveryPlan)
	return err
}

const upsertCheckIn = `-- name: UpsertCheckIn :one
INSERT INTO check_ins (
    user_id,
    checked_in_date,
    stress,
    note,
    score,
    role_snapshot,
    sleep_snapshot,
    meeting_count,
    energy_level,
    focus_quality,
    hours_worked,
    physical_symptoms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (user_id, checked_in_date)
DO UPDATE SET
    stress             = EXCLUDED.stress,
    note               = EXCLUDED.note,
    score              = EXCLUDED.score,
    role_snapshot      = EXCLUDED.role_snapshot,
    sleep_snapshot     = EXCLUDED.sleep_snapshot,
    meeting_count      = EXCLUDED.meeting_count,
    energy_level       = EXCLUDED.energy_level,
    focus_quality      = EXCLUDED.focus_quality,
    hours_worked       = EXCLUDED.hours_worked,
    physical_symptoms  = EXCLUDED.physical_symptoms,
    -- reset AI plan when check-in is meaningfully edited
    ai_recovery_plan    = CASE
                            WHEN check_ins.stress != EXCLUDED.stress
                              OR check_ins.note IS DISTINCT FROM EXCLUDED.note
                            THEN NULL
                            ELSE check_ins.ai_recovery_plan
                          END,
    ai_generated_at = CASE
                        WHEN check_ins.stress != EXCLUDED.stress
                          OR check_ins.note IS DISTINCT FROM EXCLUDED.note
                        THEN NULL
                        ELSE check_ins.ai_generated_at
                      END,
    updated_at      = NOW()
RETURNING id, user_id, checked_in_date, stress, note, score, role_snapshot, sleep_snapshot, meeting_count, ai_recovery_plan, ai_generated_at, created_at, updated_at, energy_level, focus_quality, hours_worked, physical_symptoms
`

type UpsertCheckInParams struct {
	UserID           uuid.UUID      `db:"user_id" json:"user_id"`
	CheckedInDate    pgtype.Date    `db:"checked_in_date" json:"checked_in_date"`
	Stress           int16          `db:"stress" json:"stress"`
	Note             pgtype.Text    `db:"note" json:"note"`
	Score            int16          `db:"score" json:"score"`
	RoleSnapshot     string         `db:"role_snapshot" json:"role_snapshot"`
	SleepSnapshot    int16          `db:"sleep_snapshot" json:"sleep_snapshot"`
	MeetingCount     pgtype.Int2    `db:"meeting_count" json:"meeting_count"`
	EnergyLevel      pgtype.Int2    `db:"energy_level" json:"energy_level"`
	FocusQuality     pgtype.Int2    `db:"focus_quality" json:"focus_quality"`
	HoursWorked      pgtype.Numeric `db:"hours_worked" json:"hours_worked"`
	PhysicalSymptoms []string       `db:"physical_symptoms" json:"physical_symptoms"`
}

// Allows editing today's check-in (score recomputed by the server before call).
func (q *Queries) UpsertCheckIn(ctx context.Context, arg UpsertCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, upsertCheckIn,
		arg.UserID,
		arg.CheckedInDate,
		arg.Stress,
		arg.Note,
		arg.Score,
		arg.RoleSnapshot,
		arg.SleepSnapshot,
		arg.MeetingCount,
		arg.EnergyLevel,
		arg.FocusQuality,
		arg.HoursWorked,
		arg.PhysicalSymptoms,
	)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CheckedInDate,
		&i.Stress,
		&i.Note,
		&i.Score,
		&i.RoleSnapshot,
		&i.SleepSnapshot,
		&i.MeetingCount,
		&i.AiRecoveryPlan,
		&i.AiGeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnergyLevel,
		&i.FocusQuality,
		&i.HoursWorked,
		&i.PhysicalSymptoms,
	)
	return i, err
}
