// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follow_ups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFollowUp = `-- name: CreateFollowUp :one
INSERT INTO follow_ups (
    user_id,
    fire_date,
    event_type,
    question,
    note_snippet,
    source_checkin_id
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, fire_date, event_type)
    DO NOTHING
RETURNING id, user_id, fire_date, event_type, question, note_snippet, source_checkin_id, surfaced_at, dismissed_at, expired_at, created_at
`

type CreateFollowUpParams struct {
	UserID          uuid.UUID   `db:"user_id" json:"user_id"`
	FireDate        pgtype.Date `db:"fire_date" json:"fire_date"`
	EventType       string      `db:"event_type" json:"event_type"`
	Question        string      `db:"question" json:"question"`
	NoteSnippet     pgtype.Text `db:"note_snippet" json:"note_snippet"`
	SourceCheckinID pgtype.UUID `db:"source_checkin_id" json:"source_checkin_id"`
}

func (q *Queries) CreateFollowUp(ctx context.Context, arg CreateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, createFollowUp,
		arg.UserID,
		arg.FireDate,
		arg.EventType,
		arg.Question,
		arg.NoteSnippet,
		arg.SourceCheckinID,
	)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FireDate,
		&i.EventType,
		&i.Question,
		&i.NoteSnippet,
		&i.SourceCheckinID,
		&i.SurfacedAt,
		&i.DismissedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const dismissFollowUp = `-- name: DismissFollowUp :exec
UPDATE follow_ups SET
    dismissed_at = NOW()
WHERE id      = $1
  AND user_id = $2
`

type DismissFollowUpParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DismissFollowUp(ctx context.Context, arg DismissFollowUpParams) error {
	_, err := q.db.Exec(ctx, dismissFollowUp, arg.ID, arg.UserID)
	return err
}

const expireStaleFollowUps = `-- name: ExpireStaleFollowUps :exec
UPDATE follow_ups SET
    expired_at = NOW()
WHERE fire_date   < CURRENT_DATE - 7
  AND surfaced_at IS NULL
  AND expired_at  IS NULL
`

// Cleanup cron: mark follow-ups older than 7 days that were never surfaced.
func (q *Queries) ExpireStaleFollowUps(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireStaleFollowUps)
	return err
}

const getTodayFollowUp = `-- name: GetTodayFollowUp :one
SELECT id, user_id, fire_date, event_type, question, note_snippet, source_checkin_id, surfaced_at, dismissed_at, expired_at, created_at FROM follow_ups
WHERE user_id     = $1
  AND fire_date   = $2
  AND dismissed_at IS NULL
  AND expired_at   IS NULL
ORDER BY surfaced_at NULLS FIRST
LIMIT 1
`

type GetTodayFollowUpParams struct {
	UserID   uuid.UUID   `db:"user_id" json:"user_id"`
	FireDate pgtype.Date `db:"fire_date" json:"fire_date"`
}

// Returns the single active follow-up for today (if any).
// Priority: unsurfaced follow-ups first, then ones seen but not dismissed.
func (q *Queries) GetTodayFollowUp(ctx context.Context, arg GetTodayFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, getTodayFollowUp, arg.UserID, arg.FireDate)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FireDate,
		&i.EventType,
		&i.Question,
		&i.NoteSnippet,
		&i.SourceCheckinID,
		&i.SurfacedAt,
		&i.DismissedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFollowUpsForUser = `-- name: ListFollowUpsForUser :many
SELECT id, user_id, fire_date, event_type, question, note_snippet, source_checkin_id, surfaced_at, dismissed_at, expired_at, created_at FROM follow_ups
WHERE user_id = $1
ORDER BY fire_date DESC
LIMIT $2
OFFSET $3
`

type ListFollowUpsForUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

// Used by the history/export pages to show the user their full follow-up log.
func (q *Queries) ListFollowUpsForUser(ctx context.Context, arg ListFollowUpsForUserParams) ([]FollowUp, error) {
	rows, err := q.db.Query(ctx, listFollowUpsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowUp{}
	for rows.Next() {
		var i FollowUp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FireDate,
			&i.EventType,
			&i.Question,
			&i.NoteSnippet,
			&i.SourceCheckinID,
			&i.SurfacedAt,
			&i.DismissedAt,
			&i.ExpiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFollowUpSurfaced = `-- name: MarkFollowUpSurfaced :exec
UPDATE follow_ups SET
    surfaced_at = NOW()
WHERE id      = $1
  AND user_id = $2
`

type MarkFollowUpSurfacedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkFollowUpSurfaced(ctx context.Context, arg MarkFollowUpSurfacedParams) error {
	_, err := q.db.Exec(ctx, markFollowUpSurfaced, arg.ID, arg.UserID)
	return err
}
