// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insight_metadata.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInsightMetadata = `-- name: DeleteInsightMetadata :exec
DELETE FROM insight_metadata
WHERE user_id = $1
  AND key     = $2
`

type DeleteInsightMetadataParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Key    string    `db:"key" json:"key"`
}

func (q *Queries) DeleteInsightMetadata(ctx context.Context, arg DeleteInsightMetadataParams) error {
	_, err := q.db.Exec(ctx, deleteInsightMetadata, arg.UserID, arg.Key)
	return err
}

const deleteOldDismissals = `-- name: DeleteOldDismissals :exec
DELETE FROM dismissed_components
WHERE dismissed_at < NOW() - INTERVAL '90 days'
`

// Maintenance: remove dismissals older than 90 days (they auto-expire by key).
func (q *Queries) DeleteOldDismissals(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldDismissals)
	return err
}

const dismissComponent = `-- name: DismissComponent :exec

INSERT INTO dismissed_components (user_id, component_key)
VALUES ($1, $2)
ON CONFLICT (user_id, component_key) DO NOTHING
`

type DismissComponentParams struct {
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	ComponentKey string    `db:"component_key" json:"component_key"`
}

// ── Dismissed components ──────────────────────────────────────────────────────
func (q *Queries) DismissComponent(ctx context.Context, arg DismissComponentParams) error {
	_, err := q.db.Exec(ctx, dismissComponent, arg.UserID, arg.ComponentKey)
	return err
}

const getAllInsightMetadata = `-- name: GetAllInsightMetadata :many
SELECT id, user_id, key, value, set_at, updated_at FROM insight_metadata
WHERE user_id = $1
ORDER BY key
`

// Full export for GDPR portability.
func (q *Queries) GetAllInsightMetadata(ctx context.Context, userID uuid.UUID) ([]InsightMetadatum, error) {
	rows, err := q.db.Query(ctx, getAllInsightMetadata, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightMetadatum{}
	for rows.Next() {
		var i InsightMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.SetAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsightMetadata = `-- name: GetInsightMetadata :one

SELECT id, user_id, key, value, set_at, updated_at FROM insight_metadata
WHERE user_id = $1
  AND key     = $2
`

type GetInsightMetadataParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Key    string    `db:"key" json:"key"`
}

// ── Insight metadata ──────────────────────────────────────────────────────────
func (q *Queries) GetInsightMetadata(ctx context.Context, arg GetInsightMetadataParams) (InsightMetadatum, error) {
	row := q.db.QueryRow(ctx, getInsightMetadata, arg.UserID, arg.Key)
	var i InsightMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.SetAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isComponentDismissed = `-- name: IsComponentDismissed :one
SELECT EXISTS (
    SELECT 1 FROM dismissed_components
    WHERE user_id       = $1
      AND component_key = $2
) AS dismissed
`

type IsComponentDismissedParams struct {
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	ComponentKey string    `db:"component_key" json:"component_key"`
}

func (q *Queries) IsComponentDismissed(ctx context.Context, arg IsComponentDismissedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isComponentDismissed, arg.UserID, arg.ComponentKey)
	var dismissed bool
	err := row.Scan(&dismissed)
	return dismissed, err
}

const listDismissedComponents = `-- name: ListDismissedComponents :many
SELECT component_key FROM dismissed_components
WHERE user_id = $1
  AND component_key = ANY($2::TEXT[])
`

type ListDismissedComponentsParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Column2 []string  `db:"column_2" json:"column_2"`
}

// Used when building the dashboard to batch-check dismissal state.
func (q *Queries) ListDismissedComponents(ctx context.Context, arg ListDismissedComponentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDismissedComponents, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var component_key string
		if err := rows.Scan(&component_key); err != nil {
			return nil, err
		}
		items = append(items, component_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsightMetadataByPrefix = `-- name: ListInsightMetadataByPrefix :many
SELECT id, user_id, key, value, set_at, updated_at FROM insight_metadata
WHERE user_id = $1
  AND key LIKE $2 || '%'
ORDER BY key
`

type ListInsightMetadataByPrefixParams struct {
	UserID  uuid.UUID   `db:"user_id" json:"user_id"`
	Column2 pgtype.Text `db:"column_2" json:"column_2"`
}

// Used to load all pattern-seen-dow-* keys in a single query.
func (q *Queries) ListInsightMetadataByPrefix(ctx context.Context, arg ListInsightMetadataByPrefixParams) ([]InsightMetadatum, error) {
	rows, err := q.db.Query(ctx, listInsightMetadataByPrefix, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightMetadatum{}
	for rows.Next() {
		var i InsightMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.SetAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInsightMetadata = `-- name: SetInsightMetadata :one
INSERT INTO insight_metadata (user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key)
DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = NOW()
RETURNING id, user_id, key, value, set_at, updated_at
`

type SetInsightMetadataParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Key    string      `db:"key" json:"key"`
	Value  pgtype.Text `db:"value" json:"value"`
}

func (q *Queries) SetInsightMetadata(ctx context.Context, arg SetInsightMetadataParams) (InsightMetadatum, error) {
	row := q.db.QueryRow(ctx, setInsightMetadata, arg.UserID, arg.Key, arg.Value)
	var i InsightMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.SetAt,
		&i.UpdatedAt,
	)
	return i, err
}
