// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// One row per user per calendar day. The atomic unit of all insights.
type CheckIn struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	// Local calendar date in the user's timezone — not UTC.
	CheckedInDate pgtype.Date `db:"checked_in_date" json:"checked_in_date"`
	Stress        int16       `db:"stress" json:"stress"`
	Note          pgtype.Text `db:"note" json:"note"`
	// Cognitive load score 0–100 computed server-side at insert. Higher = more load.
	Score int16 `db:"score" json:"score"`
	// Role as it was at check-in time; role changes do not rewrite history.
	RoleSnapshot  string      `db:"role_snapshot" json:"role_snapshot"`
	SleepSnapshot int16       `db:"sleep_snapshot" json:"sleep_snapshot"`
	MeetingCount  pgtype.Int2 `db:"meeting_count" json:"meeting_count"`
	// GPT-4o-mini generated plan stored as [{timing, actions[]}]; generated once.
	AiRecoveryPlan []byte             `db:"ai_recovery_plan" json:"ai_recovery_plan"`
	AiGeneratedAt  pgtype.Timestamptz `db:"ai_generated_at" json:"ai_generated_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Self-reported energy (1=depleted … 5=high). Only collected when stress >= 3.
	EnergyLevel pgtype.Int2 `db:"energy_level" json:"energy_level"`
	// Self-reported focus quality (1=scattered … 5=sharp). Only collected when stress >= 3.
	FocusQuality pgtype.Int2 `db:"focus_quality" json:"focus_quality"`
	// Hours worked today, one decimal place. Only collected when stress >= 3.
	HoursWorked pgtype.Numeric `db:"hours_worked" json:"hours_worked"`
	// Array of reported symptoms. Valid values: headache, muscle_tension, fatigue, trouble_sleeping, appetite_changes. Only collected when stress >= 4. Element validation is enforced in the application layer (CheckinSignals validator), not in the schema.
	PhysicalSymptoms []string `db:"physical_symptoms" json:"physical_symptoms"`
}

// Records which ephemeral UI cards the user has dismissed, cross-device.
type DismissedComponent struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	// Scoped key including a date/week to auto-expire old dismissals.
	ComponentKey string             `db:"component_key" json:"component_key"`
	DismissedAt  pgtype.Timestamptz `db:"dismissed_at" json:"dismissed_at"`
}

// Append-only log of all outbound emails. unique(user_id, dedup_key) prevents duplicate sends.
type EmailLog struct {
	ID       uuid.UUID   `db:"id" json:"id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Email    string      `db:"email" json:"email"`
	Template string      `db:"template" json:"template"`
	// Template + time window key. Unique constraint makes sends idempotent.
	DedupKey        pgtype.Text        `db:"dedup_key" json:"dedup_key"`
	ResendMessageID pgtype.Text        `db:"resend_message_id" json:"resend_message_id"`
	Status          string             `db:"status" json:"status"`
	ErrorMessage    pgtype.Text        `db:"error_message" json:"error_message"`
	SentAt          pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
}

// One-time tokens for email address verification. Expires after 24h.
type EmailVerification struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	Email     string             `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Forward-looking memory: events parsed from notes surfaced the day after they happen.
type FollowUp struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	// The day the follow-up question appears — typically one day after the mentioned event.
	FireDate  pgtype.Date `db:"fire_date" json:"fire_date"`
	EventType string      `db:"event_type" json:"event_type"`
	Question  string      `db:"question" json:"question"`
	// Shown verbatim in the dashboard: "Yesterday you wrote: «big deadline»"
	NoteSnippet     pgtype.Text        `db:"note_snippet" json:"note_snippet"`
	SourceCheckinID pgtype.UUID        `db:"source_checkin_id" json:"source_checkin_id"`
	SurfacedAt      pgtype.Timestamptz `db:"surfaced_at" json:"surfaced_at"`
	DismissedAt     pgtype.Timestamptz `db:"dismissed_at" json:"dismissed_at"`
	ExpiredAt       pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Per-user insight cooldowns, fire-once flags, and cached AI narratives. Replaces localStorage.
type InsightMetadatum struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	// Namespaced key. Prefix conventions: pattern-seen-, recovery-milestone-, debrief-.
	Key       string             `db:"key" json:"key"`
	Value     pgtype.Text        `db:"value" json:"value"`
	SetAt     pgtype.Timestamptz `db:"set_at" json:"set_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Append-only Paddle webhook log. Used for idempotency checks and debugging.
type PaddleEvent struct {
	ID uuid.UUID `db:"id" json:"id"`
	// Paddle's own event_id. Unique constraint prevents double-processing.
	EventID        string             `db:"event_id" json:"event_id"`
	EventType      string             `db:"event_type" json:"event_type"`
	SubscriptionID pgtype.Text        `db:"subscription_id" json:"subscription_id"`
	Payload        json.RawMessage    `db:"payload" json:"payload"`
	ProcessedAt    pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
}

// One-time tokens for password reset. Expires after 1h.
type PasswordReset struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Hashed refresh tokens for stateful JWT rotation. Rotated on every use.
type RefreshToken struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	// SHA-256(raw_token). Raw token is sent to client only once, never stored.
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Revoked   bool               `db:"revoked" json:"revoked"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Paddle subscription state. Written only by the /api/webhooks/paddle handler.
type Subscription struct {
	ID                   uuid.UUID   `db:"id" json:"id"`
	UserID               uuid.UUID   `db:"user_id" json:"user_id"`
	PaddleSubscriptionID string      `db:"paddle_subscription_id" json:"paddle_subscription_id"`
	PaddlePlanID         string      `db:"paddle_plan_id" json:"paddle_plan_id"`
	PaddleTransactionID  pgtype.Text `db:"paddle_transaction_id" json:"paddle_transaction_id"`
	PlanName             string      `db:"plan_name" json:"plan_name"`
	Currency             string      `db:"currency" json:"currency"`
	UnitPriceCents       pgtype.Int4 `db:"unit_price_cents" json:"unit_price_cents"`
	// Mirrors Paddle subscription status. Downgrade enforced at current_period_end.
	Status             string             `db:"status" json:"status"`
	TrialEndsAt        pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	CurrentPeriodStart pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	// TRUE when user cancelled but service continues until current_period_end.
	CancelAtPeriodEnd bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	CancelledAt       pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	PausedAt          pgtype.Timestamptz `db:"paused_at" json:"paused_at"`
	SeatCount         int16              `db:"seat_count" json:"seat_count"`
	LastEventType     pgtype.Text        `db:"last_event_type" json:"last_event_type"`
	LastEventAt       pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Core identity and profile. One row per registered account.
type User struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Email        string      `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	Name         string      `db:"name" json:"name"`
	// Onboarding-selected role; tunes the score engine role modifier.
	Role string `db:"role" json:"role"`
	// Self-reported normal sleep hours; drives sleep deficit signal.
	SleepBaseline int16 `db:"sleep_baseline" json:"sleep_baseline"`
	// Seeded from onboarding stress estimate; shown on Day 1 before any check-in.
	EstimatedScore    pgtype.Int2 `db:"estimated_score" json:"estimated_score"`
	CalendarConnected bool        `db:"calendar_connected" json:"calendar_connected"`
	// Encrypted Google Calendar OAuth token blob; never returned by the API.
	CalendarToken    []byte             `db:"calendar_token" json:"calendar_token"`
	CalendarSyncedAt pgtype.Timestamptz `db:"calendar_synced_at" json:"calendar_synced_at"`
	// Billing tier; controlled exclusively by Paddle webhook handler.
	Tier             string             `db:"tier" json:"tier"`
	PaddleCustomerID pgtype.Text        `db:"paddle_customer_id" json:"paddle_customer_id"`
	Timezone         string             `db:"timezone" json:"timezone"`
	EmailVerified    bool               `db:"email_verified" json:"email_verified"`
	GoogleID         pgtype.Text        `db:"google_id" json:"google_id"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Per-user notification opt-in/-out. Upserted on settings save.
type UserNotificationPref struct {
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	CheckinReminder bool      `db:"checkin_reminder" json:"checkin_reminder"`
	// Local time to fire the check-in reminder, in the user's own timezone.
	ReminderTime       pgtype.Time        `db:"reminder_time" json:"reminder_time"`
	MondayDebriefEmail bool               `db:"monday_debrief_email" json:"monday_debrief_email"`
	WeeklySummaryEmail bool               `db:"weekly_summary_email" json:"weekly_summary_email"`
	StreakAlertEmail   bool               `db:"streak_alert_email" json:"streak_alert_email"`
	PatternEmail       bool               `db:"pattern_email" json:"pattern_email"`
	ReEngageEmail      bool               `db:"re_engage_email" json:"re_engage_email"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
