// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultNotificationPrefs = `-- name: CreateDefaultNotificationPrefs :one
INSERT INTO user_notification_prefs (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, checkin_reminder, reminder_time, monday_debrief_email, weekly_summary_email, streak_alert_email, pattern_email, re_engage_email, updated_at
`

// Called automatically on user registration.
func (q *Queries) CreateDefaultNotificationPrefs(ctx context.Context, userID uuid.UUID) (UserNotificationPref, error) {
	row := q.db.QueryRow(ctx, createDefaultNotificationPrefs, userID)
	var i UserNotificationPref
	err := row.Scan(
		&i.UserID,
		&i.CheckinReminder,
		&i.ReminderTime,
		&i.MondayDebriefEmail,
		&i.WeeklySummaryEmail,
		&i.StreakAlertEmail,
		&i.PatternEmail,
		&i.ReEngageEmail,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailLog = `-- name: CreateEmailLog :one

INSERT INTO email_logs (
    user_id,
    email,
    template,
    dedup_key,
    resend_message_id,
    status
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, email, template, dedup_key, resend_message_id, status, error_message, sent_at
`

type CreateEmailLogParams struct {
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	Email           string      `db:"email" json:"email"`
	Template        string      `db:"template" json:"template"`
	DedupKey        pgtype.Text `db:"dedup_key" json:"dedup_key"`
	ResendMessageID pgtype.Text `db:"resend_message_id" json:"resend_message_id"`
	Status          string      `db:"status" json:"status"`
}

// ── Email logs ────────────────────────────────────────────────────────────────
func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRow(ctx, createEmailLog,
		arg.UserID,
		arg.Email,
		arg.Template,
		arg.DedupKey,
		arg.ResendMessageID,
		arg.Status,
	)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Template,
		&i.DedupKey,
		&i.ResendMessageID,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
	)
	return i, err
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :one
SELECT user_id, checkin_reminder, reminder_time, monday_debrief_email, weekly_summary_email, streak_alert_email, pattern_email, re_engage_email, updated_at FROM user_notification_prefs
WHERE user_id = $1
`

func (q *Queries) GetNotificationPrefs(ctx context.Context, userID uuid.UUID) (UserNotificationPref, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, userID)
	var i UserNotificationPref
	err := row.Scan(
		&i.UserID,
		&i.CheckinReminder,
		&i.ReminderTime,
		&i.MondayDebriefEmail,
		&i.WeeklySummaryEmail,
		&i.StreakAlertEmail,
		&i.PatternEmail,
		&i.ReEngageEmail,
		&i.UpdatedAt,
	)
	return i, err
}

const isEmailAlreadySent = `-- name: IsEmailAlreadySent :one
SELECT EXISTS (
    SELECT 1 FROM email_logs
    WHERE user_id   = $1
      AND dedup_key = $2
      AND status    = 'sent'
) AS already_sent
`

type IsEmailAlreadySentParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	DedupKey pgtype.Text `db:"dedup_key" json:"dedup_key"`
}

// Guards against duplicate sends. Returns true if the dedup_key has
// already been sent successfully for this user.
func (q *Queries) IsEmailAlreadySent(ctx context.Context, arg IsEmailAlreadySentParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailAlreadySent, arg.UserID, arg.DedupKey)
	var already_sent bool
	err := row.Scan(&already_sent)
	return already_sent, err
}

const listRecentEmailsForUser = `-- name: ListRecentEmailsForUser :many
SELECT
    template,
    dedup_key,
    status,
    sent_at
FROM email_logs
WHERE user_id = $1
ORDER BY sent_at DESC
LIMIT $2
`

type ListRecentEmailsForUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
}

type ListRecentEmailsForUserRow struct {
	Template string             `db:"template" json:"template"`
	DedupKey pgtype.Text        `db:"dedup_key" json:"dedup_key"`
	Status   string             `db:"status" json:"status"`
	SentAt   pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
}

func (q *Queries) ListRecentEmailsForUser(ctx context.Context, arg ListRecentEmailsForUserParams) ([]ListRecentEmailsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRecentEmailsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentEmailsForUserRow{}
	for rows.Next() {
		var i ListRecentEmailsForUserRow
		if err := rows.Scan(
			&i.Template,
			&i.DedupKey,
			&i.Status,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailFailed = `-- name: MarkEmailFailed :exec
UPDATE email_logs SET
    status        = 'failed',
    error_message = $2
WHERE id = $1
`

type MarkEmailFailedParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
}

func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error {
	_, err := q.db.Exec(ctx, markEmailFailed, arg.ID, arg.ErrorMessage)
	return err
}

const upsertNotificationPrefs = `-- name: UpsertNotificationPrefs :one

INSERT INTO user_notification_prefs (
    user_id,
    checkin_reminder,
    reminder_time,
    monday_debrief_email,
    weekly_summary_email,
    streak_alert_email,
    pattern_email,
    re_engage_email
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id)
DO UPDATE SET
    checkin_reminder        = EXCLUDED.checkin_reminder,
    reminder_time           = EXCLUDED.reminder_time,
    monday_debrief_email    = EXCLUDED.monday_debrief_email,
    weekly_summary_email    = EXCLUDED.weekly_summary_email,
    streak_alert_email      = EXCLUDED.streak_alert_email,
    pattern_email           = EXCLUDED.pattern_email,
    re_engage_email         = EXCLUDED.re_engage_email,
    updated_at              = NOW()
RETURNING user_id, checkin_reminder, reminder_time, monday_debrief_email, weekly_summary_email, streak_alert_email, pattern_email, re_engage_email, updated_at
`

type UpsertNotificationPrefsParams struct {
	UserID             uuid.UUID   `db:"user_id" json:"user_id"`
	CheckinReminder    bool        `db:"checkin_reminder" json:"checkin_reminder"`
	ReminderTime       pgtype.Time `db:"reminder_time" json:"reminder_time"`
	MondayDebriefEmail bool        `db:"monday_debrief_email" json:"monday_debrief_email"`
	WeeklySummaryEmail bool        `db:"weekly_summary_email" json:"weekly_summary_email"`
	StreakAlertEmail   bool        `db:"streak_alert_email" json:"streak_alert_email"`
	PatternEmail       bool        `db:"pattern_email" json:"pattern_email"`
	ReEngageEmail      bool        `db:"re_engage_email" json:"re_engage_email"`
}

// ── Notification preferences ──────────────────────────────────────────────────
func (q *Queries) UpsertNotificationPrefs(ctx context.Context, arg UpsertNotificationPrefsParams) (UserNotificationPref, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPrefs,
		arg.UserID,
		arg.CheckinReminder,
		arg.ReminderTime,
		arg.MondayDebriefEmail,
		arg.WeeklySummaryEmail,
		arg.StreakAlertEmail,
		arg.PatternEmail,
		arg.ReEngageEmail,
	)
	var i UserNotificationPref
	err := row.Scan(
		&i.UserID,
		&i.CheckinReminder,
		&i.ReminderTime,
		&i.MondayDebriefEmail,
		&i.WeeklySummaryEmail,
		&i.StreakAlertEmail,
		&i.PatternEmail,
		&i.ReEngageEmail,
		&i.UpdatedAt,
	)
	return i, err
}
