// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEFTPayment = `-- name: CreateEFTPayment :one

INSERT INTO eft_payments (
    user_id,
    reference,
    amount_cents,
    currency,
    plan_name,
    status,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, reference, amount_cents, currency, plan_name, status, proof_image_url, verified_by, verified_at, rejection_note, expires_at, created_at, updated_at
`

type CreateEFTPaymentParams struct {
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Reference   string             `db:"reference" json:"reference"`
	AmountCents int32              `db:"amount_cents" json:"amount_cents"`
	Currency    string             `db:"currency" json:"currency"`
	PlanName    string             `db:"plan_name" json:"plan_name"`
	Status      string             `db:"status" json:"status"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// ── EFT Payments ───────────────────────────────────────────────────────────────
func (q *Queries) CreateEFTPayment(ctx context.Context, arg CreateEFTPaymentParams) (EftPayment, error) {
	row := q.db.QueryRow(ctx, createEFTPayment,
		arg.UserID,
		arg.Reference,
		arg.AmountCents,
		arg.Currency,
		arg.PlanName,
		arg.Status,
		arg.ExpiresAt,
	)
	var i EftPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reference,
		&i.AmountCents,
		&i.Currency,
		&i.PlanName,
		&i.Status,
		&i.ProofImageUrl,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionNote,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireEFTPayments = `-- name: ExpireEFTPayments :many
UPDATE eft_payments SET
    status     = 'expired',
    updated_at = NOW()
WHERE status = 'pending'
  AND expires_at <= NOW()
RETURNING id, user_id, reference, amount_cents, currency, plan_name, status, proof_image_url, verified_by, verified_at, rejection_note, expires_at, created_at, updated_at
`

// Mark expired payments as expired (called by maintenance job)
func (q *Queries) ExpireEFTPayments(ctx context.Context) ([]EftPayment, error) {
	rows, err := q.db.Query(ctx, expireEFTPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EftPayment{}
	for rows.Next() {
		var i EftPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reference,
			&i.AmountCents,
			&i.Currency,
			&i.PlanName,
			&i.Status,
			&i.ProofImageUrl,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionNote,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEFTPaymentByID = `-- name: GetEFTPaymentByID :one
SELECT id, user_id, reference, amount_cents, currency, plan_name, status, proof_image_url, verified_by, verified_at, rejection_note, expires_at, created_at, updated_at FROM eft_payments
WHERE id = $1
`

func (q *Queries) GetEFTPaymentByID(ctx context.Context, id uuid.UUID) (EftPayment, error) {
	row := q.db.QueryRow(ctx, getEFTPaymentByID, id)
	var i EftPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reference,
		&i.AmountCents,
		&i.Currency,
		&i.PlanName,
		&i.Status,
		&i.ProofImageUrl,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionNote,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEFTPaymentByReference = `-- name: GetEFTPaymentByReference :one
SELECT id, user_id, reference, amount_cents, currency, plan_name, status, proof_image_url, verified_by, verified_at, rejection_note, expires_at, created_at, updated_at FROM eft_payments
WHERE reference = $1
`

func (q *Queries) GetEFTPaymentByReference(ctx context.Context, reference string) (EftPayment, error) {
	row := q.db.QueryRow(ctx, getEFTPaymentByReference, reference)
	var i EftPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reference,
		&i.AmountCents,
		&i.Currency,
		&i.PlanName,
		&i.Status,
		&i.ProofImageUrl,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionNote,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEFTPaymentByUserID = `-- name: GetEFTPaymentByUserID :many
SELECT id, user_id, reference, amount_cents, currency, plan_name, status, proof_image_url, verified_by, verified_at, rejection_note, expires_at, created_at, updated_at FROM eft_payments
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetEFTPaymentByUserID(ctx context.Context, userID uuid.UUID) ([]EftPayment, error) {
	rows, err := q.db.Query(ctx, getEFTPaymentByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EftPayment{}
	for rows.Next() {
		var i EftPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reference,
			&i.AmountCents,
			&i.Currency,
			&i.PlanName,
			&i.Status,
			&i.ProofImageUrl,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionNote,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingEFTPayments = `-- name: GetPendingEFTPayments :many
SELECT id, user_id, reference, amount_cents, currency, plan_name, status, proof_image_url, verified_by, verified_at, rejection_note, expires_at, created_at, updated_at FROM eft_payments
WHERE status = 'pending'
  AND expires_at > NOW()
ORDER BY created_at ASC
`

func (q *Queries) GetPendingEFTPayments(ctx context.Context) ([]EftPayment, error) {
	rows, err := q.db.Query(ctx, getPendingEFTPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EftPayment{}
	for rows.Next() {
		var i EftPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reference,
			&i.AmountCents,
			&i.Currency,
			&i.PlanName,
			&i.Status,
			&i.ProofImageUrl,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionNote,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEFTPaymentStatus = `-- name: UpdateEFTPaymentStatus :exec
UPDATE eft_payments SET
    status         = $2,
    verified_by    = $3,
    verified_at    = $4,
    rejection_note = $5,
    updated_at     = NOW()
WHERE id = $1
`

type UpdateEFTPaymentStatusParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Status        string             `db:"status" json:"status"`
	VerifiedBy    pgtype.UUID        `db:"verified_by" json:"verified_by"`
	VerifiedAt    pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	RejectionNote pgtype.Text        `db:"rejection_note" json:"rejection_note"`
}

func (q *Queries) UpdateEFTPaymentStatus(ctx context.Context, arg UpdateEFTPaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateEFTPaymentStatus,
		arg.ID,
		arg.Status,
		arg.VerifiedBy,
		arg.VerifiedAt,
		arg.RejectionNote,
	)
	return err
}
