// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_feedback.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFeedbackCountsByKey = `-- name: GetFeedbackCountsByKey :many
SELECT
    recommended_action_key,
    COUNT(*) FILTER (WHERE helpful = true) as helpful_count,
    COUNT(*) FILTER (WHERE helpful = false) as not_helpful_count,
    COUNT(*) as total_count
FROM recommendation_feedback
WHERE user_id = $1
AND created_at >= $2
GROUP BY recommended_action_key
`

type GetFeedbackCountsByKeyParams struct {
	UserID uuid.UUID          `db:"user_id" json:"user_id"`
	Since  pgtype.Timestamptz `db:"since" json:"since"`
}

type GetFeedbackCountsByKeyRow struct {
	RecommendedActionKey string `db:"recommended_action_key" json:"recommended_action_key"`
	HelpfulCount         int64  `db:"helpful_count" json:"helpful_count"`
	NotHelpfulCount      int64  `db:"not_helpful_count" json:"not_helpful_count"`
	TotalCount           int64  `db:"total_count" json:"total_count"`
}

func (q *Queries) GetFeedbackCountsByKey(ctx context.Context, arg GetFeedbackCountsByKeyParams) ([]GetFeedbackCountsByKeyRow, error) {
	rows, err := q.db.Query(ctx, getFeedbackCountsByKey, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeedbackCountsByKeyRow{}
	for rows.Next() {
		var i GetFeedbackCountsByKeyRow
		if err := rows.Scan(
			&i.RecommendedActionKey,
			&i.HelpfulCount,
			&i.NotHelpfulCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayFeedback = `-- name: GetTodayFeedback :one
SELECT id, user_id, recommended_action_key, helpful, check_in_id, feedback_date, created_at FROM recommendation_feedback
WHERE user_id = $1
AND recommended_action_key = $2
AND feedback_date = CURRENT_DATE
`

type GetTodayFeedbackParams struct {
	UserID               uuid.UUID `db:"user_id" json:"user_id"`
	RecommendedActionKey string    `db:"recommended_action_key" json:"recommended_action_key"`
}

func (q *Queries) GetTodayFeedback(ctx context.Context, arg GetTodayFeedbackParams) (RecommendationFeedback, error) {
	row := q.db.QueryRow(ctx, getTodayFeedback, arg.UserID, arg.RecommendedActionKey)
	var i RecommendationFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendedActionKey,
		&i.Helpful,
		&i.CheckInID,
		&i.FeedbackDate,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentFeedback = `-- name: ListRecentFeedback :many
SELECT id, user_id, recommended_action_key, helpful, check_in_id, feedback_date, created_at FROM recommendation_feedback
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentFeedbackParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	N      int32     `db:"n" json:"n"`
}

func (q *Queries) ListRecentFeedback(ctx context.Context, arg ListRecentFeedbackParams) ([]RecommendationFeedback, error) {
	rows, err := q.db.Query(ctx, listRecentFeedback, arg.UserID, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationFeedback{}
	for rows.Next() {
		var i RecommendationFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecommendedActionKey,
			&i.Helpful,
			&i.CheckInID,
			&i.FeedbackDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecommendationFeedback = `-- name: UpsertRecommendationFeedback :one
INSERT INTO recommendation_feedback (
    user_id,
    recommended_action_key,
    helpful,
    check_in_id
) VALUES (
    $1,
    $2,
    $3,
    $4
) ON CONFLICT (user_id, recommended_action_key, feedback_date)
DO UPDATE SET
    helpful = $3,
    created_at = NOW()
RETURNING id, user_id, recommended_action_key, helpful, check_in_id, feedback_date, created_at
`

type UpsertRecommendationFeedbackParams struct {
	UserID               uuid.UUID   `db:"user_id" json:"user_id"`
	RecommendedActionKey string      `db:"recommended_action_key" json:"recommended_action_key"`
	Helpful              bool        `db:"helpful" json:"helpful"`
	CheckInID            pgtype.UUID `db:"check_in_id" json:"check_in_id"`
}

func (q *Queries) UpsertRecommendationFeedback(ctx context.Context, arg UpsertRecommendationFeedbackParams) (RecommendationFeedback, error) {
	row := q.db.QueryRow(ctx, upsertRecommendationFeedback,
		arg.UserID,
		arg.RecommendedActionKey,
		arg.Helpful,
		arg.CheckInID,
	)
	var i RecommendationFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendedActionKey,
		&i.Helpful,
		&i.CheckInID,
		&i.FeedbackDate,
		&i.CreatedAt,
	)
	return i, err
}
