// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_commitments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecommendationCommitment = `-- name: CreateRecommendationCommitment :one
INSERT INTO recommendation_commitments (
    user_id,
    recommendation_key,
    recommendation_title,
    recommendation_detail,
    why_this_action,
    why_now,
    target_day,
    basis_kind,
    basis_state,
    predicted_score_delta,
    status,
    committed_at,
    due_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, user_id, recommendation_key, recommendation_title, recommendation_detail, why_this_action, why_now, target_day, basis_kind, basis_state, predicted_score_delta, status, committed_at, due_at, completed_at, outcome_helpfulness, evaluated_at, created_at, updated_at
`

type CreateRecommendationCommitmentParams struct {
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	RecommendationKey    string             `db:"recommendation_key" json:"recommendation_key"`
	RecommendationTitle  string             `db:"recommendation_title" json:"recommendation_title"`
	RecommendationDetail string             `db:"recommendation_detail" json:"recommendation_detail"`
	WhyThisAction        string             `db:"why_this_action" json:"why_this_action"`
	WhyNow               string             `db:"why_now" json:"why_now"`
	TargetDay            string             `db:"target_day" json:"target_day"`
	BasisKind            string             `db:"basis_kind" json:"basis_kind"`
	BasisState           string             `db:"basis_state" json:"basis_state"`
	PredictedScoreDelta  int32              `db:"predicted_score_delta" json:"predicted_score_delta"`
	Status               string             `db:"status" json:"status"`
	CommittedAt          pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
	DueAt                pgtype.Timestamptz `db:"due_at" json:"due_at"`
}

func (q *Queries) CreateRecommendationCommitment(ctx context.Context, arg CreateRecommendationCommitmentParams) (RecommendationCommitment, error) {
	row := q.db.QueryRow(ctx, createRecommendationCommitment,
		arg.UserID,
		arg.RecommendationKey,
		arg.RecommendationTitle,
		arg.RecommendationDetail,
		arg.WhyThisAction,
		arg.WhyNow,
		arg.TargetDay,
		arg.BasisKind,
		arg.BasisState,
		arg.PredictedScoreDelta,
		arg.Status,
		arg.CommittedAt,
		arg.DueAt,
	)
	var i RecommendationCommitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendationKey,
		&i.RecommendationTitle,
		&i.RecommendationDetail,
		&i.WhyThisAction,
		&i.WhyNow,
		&i.TargetDay,
		&i.BasisKind,
		&i.BasisState,
		&i.PredictedScoreDelta,
		&i.Status,
		&i.CommittedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.OutcomeHelpfulness,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireRecommendationCommitment = `-- name: ExpireRecommendationCommitment :one
UPDATE recommendation_commitments
SET status = 'expired'
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, recommendation_key, recommendation_title, recommendation_detail, why_this_action, why_now, target_day, basis_kind, basis_state, predicted_score_delta, status, committed_at, due_at, completed_at, outcome_helpfulness, evaluated_at, created_at, updated_at
`

type ExpireRecommendationCommitmentParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ExpireRecommendationCommitment(ctx context.Context, arg ExpireRecommendationCommitmentParams) (RecommendationCommitment, error) {
	row := q.db.QueryRow(ctx, expireRecommendationCommitment, arg.ID, arg.UserID)
	var i RecommendationCommitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendationKey,
		&i.RecommendationTitle,
		&i.RecommendationDetail,
		&i.WhyThisAction,
		&i.WhyNow,
		&i.TargetDay,
		&i.BasisKind,
		&i.BasisState,
		&i.PredictedScoreDelta,
		&i.Status,
		&i.CommittedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.OutcomeHelpfulness,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRecommendationCommitment = `-- name: GetActiveRecommendationCommitment :one
SELECT id, user_id, recommendation_key, recommendation_title, recommendation_detail, why_this_action, why_now, target_day, basis_kind, basis_state, predicted_score_delta, status, committed_at, due_at, completed_at, outcome_helpfulness, evaluated_at, created_at, updated_at
FROM recommendation_commitments
WHERE user_id = $1
  AND status IN ('committed', 'completed')
ORDER BY committed_at DESC
LIMIT 1
`

func (q *Queries) GetActiveRecommendationCommitment(ctx context.Context, userID uuid.UUID) (RecommendationCommitment, error) {
	row := q.db.QueryRow(ctx, getActiveRecommendationCommitment, userID)
	var i RecommendationCommitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendationKey,
		&i.RecommendationTitle,
		&i.RecommendationDetail,
		&i.WhyThisAction,
		&i.WhyNow,
		&i.TargetDay,
		&i.BasisKind,
		&i.BasisState,
		&i.PredictedScoreDelta,
		&i.Status,
		&i.CommittedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.OutcomeHelpfulness,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecommendationCommitmentByID = `-- name: GetRecommendationCommitmentByID :one
SELECT id, user_id, recommendation_key, recommendation_title, recommendation_detail, why_this_action, why_now, target_day, basis_kind, basis_state, predicted_score_delta, status, committed_at, due_at, completed_at, outcome_helpfulness, evaluated_at, created_at, updated_at
FROM recommendation_commitments
WHERE id = $1
  AND user_id = $2
`

type GetRecommendationCommitmentByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetRecommendationCommitmentByID(ctx context.Context, arg GetRecommendationCommitmentByIDParams) (RecommendationCommitment, error) {
	row := q.db.QueryRow(ctx, getRecommendationCommitmentByID, arg.ID, arg.UserID)
	var i RecommendationCommitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendationKey,
		&i.RecommendationTitle,
		&i.RecommendationDetail,
		&i.WhyThisAction,
		&i.WhyNow,
		&i.TargetDay,
		&i.BasisKind,
		&i.BasisState,
		&i.PredictedScoreDelta,
		&i.Status,
		&i.CommittedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.OutcomeHelpfulness,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRecommendationCommitmentOutcome = `-- name: SetRecommendationCommitmentOutcome :one
UPDATE recommendation_commitments
SET
    outcome_helpfulness = $1,
    status = 'evaluated',
    evaluated_at = NOW()
WHERE id = $2
  AND user_id = $3
RETURNING id, user_id, recommendation_key, recommendation_title, recommendation_detail, why_this_action, why_now, target_day, basis_kind, basis_state, predicted_score_delta, status, committed_at, due_at, completed_at, outcome_helpfulness, evaluated_at, created_at, updated_at
`

type SetRecommendationCommitmentOutcomeParams struct {
	OutcomeHelpfulness pgtype.Text `db:"outcome_helpfulness" json:"outcome_helpfulness"`
	ID                 uuid.UUID   `db:"id" json:"id"`
	UserID             uuid.UUID   `db:"user_id" json:"user_id"`
}

func (q *Queries) SetRecommendationCommitmentOutcome(ctx context.Context, arg SetRecommendationCommitmentOutcomeParams) (RecommendationCommitment, error) {
	row := q.db.QueryRow(ctx, setRecommendationCommitmentOutcome, arg.OutcomeHelpfulness, arg.ID, arg.UserID)
	var i RecommendationCommitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendationKey,
		&i.RecommendationTitle,
		&i.RecommendationDetail,
		&i.WhyThisAction,
		&i.WhyNow,
		&i.TargetDay,
		&i.BasisKind,
		&i.BasisState,
		&i.PredictedScoreDelta,
		&i.Status,
		&i.CommittedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.OutcomeHelpfulness,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecommendationCommitmentStatus = `-- name: UpdateRecommendationCommitmentStatus :one
UPDATE recommendation_commitments
SET
    status = $1,
    completed_at = COALESCE($2, completed_at)
WHERE id = $3
  AND user_id = $4
RETURNING id, user_id, recommendation_key, recommendation_title, recommendation_detail, why_this_action, why_now, target_day, basis_kind, basis_state, predicted_score_delta, status, committed_at, due_at, completed_at, outcome_helpfulness, evaluated_at, created_at, updated_at
`

type UpdateRecommendationCommitmentStatusParams struct {
	Status      string             `db:"status" json:"status"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateRecommendationCommitmentStatus(ctx context.Context, arg UpdateRecommendationCommitmentStatusParams) (RecommendationCommitment, error) {
	row := q.db.QueryRow(ctx, updateRecommendationCommitmentStatus,
		arg.Status,
		arg.CompletedAt,
		arg.ID,
		arg.UserID,
	)
	var i RecommendationCommitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecommendationKey,
		&i.RecommendationTitle,
		&i.RecommendationDetail,
		&i.WhyThisAction,
		&i.WhyNow,
		&i.TargetDay,
		&i.BasisKind,
		&i.BasisState,
		&i.PredictedScoreDelta,
		&i.Status,
		&i.CommittedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.OutcomeHelpfulness,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
