// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions SET
    status               = 'cancelled',
    cancel_at_period_end = TRUE,
    cancelled_at         = NOW(),
    last_event_type      = 'subscription.cancelled',
    last_event_at        = NOW()
WHERE paddle_subscription_id = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, paddleSubscriptionID string) error {
	_, err := q.db.Exec(ctx, cancelSubscription, paddleSubscriptionID)
	return err
}

const createPaddleEvent = `-- name: CreatePaddleEvent :one

INSERT INTO paddle_events (
    event_id,
    event_type,
    subscription_id,
    payload
) VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id) DO NOTHING
RETURNING id, event_id, event_type, subscription_id, payload, processed_at
`

type CreatePaddleEventParams struct {
	EventID        string          `db:"event_id" json:"event_id"`
	EventType      string          `db:"event_type" json:"event_type"`
	SubscriptionID pgtype.Text     `db:"subscription_id" json:"subscription_id"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
}

// ── Paddle events ────────────────────────────────────────────────────────────
func (q *Queries) CreatePaddleEvent(ctx context.Context, arg CreatePaddleEventParams) (PaddleEvent, error) {
	row := q.db.QueryRow(ctx, createPaddleEvent,
		arg.EventID,
		arg.EventType,
		arg.SubscriptionID,
		arg.Payload,
	)
	var i PaddleEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.SubscriptionID,
		&i.Payload,
		&i.ProcessedAt,
	)
	return i, err
}

const getActiveSubscriptionByUserID = `-- name: GetActiveSubscriptionByUserID :one
SELECT id, user_id, paddle_subscription_id, paddle_plan_id, paddle_transaction_id, plan_name, currency, unit_price_cents, status, trial_ends_at, current_period_start, current_period_end, cancel_at_period_end, cancelled_at, paused_at, seat_count, last_event_type, last_event_at, created_at, updated_at FROM subscriptions
WHERE user_id = $1
  AND status IN ('active', 'trialing')
ORDER BY current_period_end DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaddleSubscriptionID,
		&i.PaddlePlanID,
		&i.PaddleTransactionID,
		&i.PlanName,
		&i.Currency,
		&i.UnitPriceCents,
		&i.Status,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.PausedAt,
		&i.SeatCount,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByPaddleID = `-- name: GetSubscriptionByPaddleID :one
SELECT id, user_id, paddle_subscription_id, paddle_plan_id, paddle_transaction_id, plan_name, currency, unit_price_cents, status, trial_ends_at, current_period_start, current_period_end, cancel_at_period_end, cancelled_at, paused_at, seat_count, last_event_type, last_event_at, created_at, updated_at FROM subscriptions
WHERE paddle_subscription_id = $1
`

func (q *Queries) GetSubscriptionByPaddleID(ctx context.Context, paddleSubscriptionID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByPaddleID, paddleSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaddleSubscriptionID,
		&i.PaddlePlanID,
		&i.PaddleTransactionID,
		&i.PlanName,
		&i.Currency,
		&i.UnitPriceCents,
		&i.Status,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.PausedAt,
		&i.SeatCount,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredSubscriptions = `-- name: ListExpiredSubscriptions :many
SELECT s.id, s.user_id, s.paddle_subscription_id, s.paddle_plan_id, s.paddle_transaction_id, s.plan_name, s.currency, s.unit_price_cents, s.status, s.trial_ends_at, s.current_period_start, s.current_period_end, s.cancel_at_period_end, s.cancelled_at, s.paused_at, s.seat_count, s.last_event_type, s.last_event_at, s.created_at, s.updated_at, u.id AS uid
FROM subscriptions s
JOIN users u ON u.id = s.user_id
WHERE s.cancel_at_period_end = TRUE
  AND s.current_period_end   < NOW()
  AND s.status               != 'cancelled'
`

type ListExpiredSubscriptionsRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	PaddleSubscriptionID string             `db:"paddle_subscription_id" json:"paddle_subscription_id"`
	PaddlePlanID         string             `db:"paddle_plan_id" json:"paddle_plan_id"`
	PaddleTransactionID  pgtype.Text        `db:"paddle_transaction_id" json:"paddle_transaction_id"`
	PlanName             string             `db:"plan_name" json:"plan_name"`
	Currency             string             `db:"currency" json:"currency"`
	UnitPriceCents       pgtype.Int4        `db:"unit_price_cents" json:"unit_price_cents"`
	Status               string             `db:"status" json:"status"`
	TrialEndsAt          pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	CurrentPeriodStart   pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	CancelAtPeriodEnd    bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	CancelledAt          pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	PausedAt             pgtype.Timestamptz `db:"paused_at" json:"paused_at"`
	SeatCount            int16              `db:"seat_count" json:"seat_count"`
	LastEventType        pgtype.Text        `db:"last_event_type" json:"last_event_type"`
	LastEventAt          pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Uid                  uuid.UUID          `db:"uid" json:"uid"`
}

// Used by the hourly cron to downgrade users whose subscription period ended.
func (q *Queries) ListExpiredSubscriptions(ctx context.Context) ([]ListExpiredSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredSubscriptionsRow{}
	for rows.Next() {
		var i ListExpiredSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaddleSubscriptionID,
			&i.PaddlePlanID,
			&i.PaddleTransactionID,
			&i.PlanName,
			&i.Currency,
			&i.UnitPriceCents,
			&i.Status,
			&i.TrialEndsAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
			&i.CancelledAt,
			&i.PausedAt,
			&i.SeatCount,
			&i.LastEventType,
			&i.LastEventAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paddleEventExists = `-- name: PaddleEventExists :one
SELECT EXISTS (
    SELECT 1 FROM paddle_events WHERE event_id = $1
) AS exists
`

func (q *Queries) PaddleEventExists(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, paddleEventExists, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSubscriptionPastDue = `-- name: SetSubscriptionPastDue :exec
UPDATE subscriptions SET
    status          = 'past_due',
    last_event_type = 'payment.failed',
    last_event_at   = NOW()
WHERE paddle_subscription_id = $1
`

func (q *Queries) SetSubscriptionPastDue(ctx context.Context, paddleSubscriptionID string) error {
	_, err := q.db.Exec(ctx, setSubscriptionPastDue, paddleSubscriptionID)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :one

INSERT INTO subscriptions (
    user_id,
    paddle_subscription_id,
    paddle_plan_id,
    paddle_transaction_id,
    plan_name,
    currency,
    unit_price_cents,
    status,
    trial_ends_at,
    current_period_start,
    current_period_end,
    cancel_at_period_end,
    seat_count,
    last_event_type,
    last_event_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (paddle_subscription_id)
DO UPDATE SET
    paddle_plan_id          = EXCLUDED.paddle_plan_id,
    paddle_transaction_id   = EXCLUDED.paddle_transaction_id,
    plan_name               = EXCLUDED.plan_name,
    currency                = EXCLUDED.currency,
    unit_price_cents        = EXCLUDED.unit_price_cents,
    status                  = EXCLUDED.status,
    trial_ends_at           = EXCLUDED.trial_ends_at,
    current_period_start    = EXCLUDED.current_period_start,
    current_period_end      = EXCLUDED.current_period_end,
    cancel_at_period_end    = EXCLUDED.cancel_at_period_end,
    seat_count              = EXCLUDED.seat_count,
    last_event_type         = EXCLUDED.last_event_type,
    last_event_at           = EXCLUDED.last_event_at,
    updated_at              = NOW()
RETURNING id, user_id, paddle_subscription_id, paddle_plan_id, paddle_transaction_id, plan_name, currency, unit_price_cents, status, trial_ends_at, current_period_start, current_period_end, cancel_at_period_end, cancelled_at, paused_at, seat_count, last_event_type, last_event_at, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	PaddleSubscriptionID string             `db:"paddle_subscription_id" json:"paddle_subscription_id"`
	PaddlePlanID         string             `db:"paddle_plan_id" json:"paddle_plan_id"`
	PaddleTransactionID  pgtype.Text        `db:"paddle_transaction_id" json:"paddle_transaction_id"`
	PlanName             string             `db:"plan_name" json:"plan_name"`
	Currency             string             `db:"currency" json:"currency"`
	UnitPriceCents       pgtype.Int4        `db:"unit_price_cents" json:"unit_price_cents"`
	Status               string             `db:"status" json:"status"`
	TrialEndsAt          pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	CurrentPeriodStart   pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	CancelAtPeriodEnd    bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	SeatCount            int16              `db:"seat_count" json:"seat_count"`
	LastEventType        pgtype.Text        `db:"last_event_type" json:"last_event_type"`
	LastEventAt          pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
}

// ── Subscriptions ────────────────────────────────────────────────────────────
// Called by the Paddle webhook handler for subscription.created and
// subscription.updated events. Idempotent on paddle_subscription_id.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.UserID,
		arg.PaddleSubscriptionID,
		arg.PaddlePlanID,
		arg.PaddleTransactionID,
		arg.PlanName,
		arg.Currency,
		arg.UnitPriceCents,
		arg.Status,
		arg.TrialEndsAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.SeatCount,
		arg.LastEventType,
		arg.LastEventAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaddleSubscriptionID,
		&i.PaddlePlanID,
		&i.PaddleTransactionID,
		&i.PlanName,
		&i.Currency,
		&i.UnitPriceCents,
		&i.Status,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.PausedAt,
		&i.SeatCount,
		&i.LastEventType,
		&i.LastEventAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
