// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearCalendarToken = `-- name: ClearCalendarToken :exec
UPDATE users SET
    calendar_token      = NULL,
    calendar_connected  = FALSE,
    calendar_synced_at  = NULL
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) ClearCalendarToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCalendarToken, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    name,
    role,
    sleep_baseline,
    estimated_score,
    timezone,
    google_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, email, password_hash, name, role, sleep_baseline, estimated_score, calendar_connected, calendar_token, calendar_synced_at, tier, paddle_customer_id, timezone, email_verified, google_id, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email          string      `db:"email" json:"email"`
	PasswordHash   pgtype.Text `db:"password_hash" json:"password_hash"`
	Name           string      `db:"name" json:"name"`
	Role           string      `db:"role" json:"role"`
	SleepBaseline  int16       `db:"sleep_baseline" json:"sleep_baseline"`
	EstimatedScore pgtype.Int2 `db:"estimated_score" json:"estimated_score"`
	Timezone       string      `db:"timezone" json:"timezone"`
	GoogleID       pgtype.Text `db:"google_id" json:"google_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.SleepBaseline,
		arg.EstimatedScore,
		arg.Timezone,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.SleepBaseline,
		&i.EstimatedScore,
		&i.CalendarConnected,
		&i.CalendarToken,
		&i.CalendarSyncedAt,
		&i.Tier,
		&i.PaddleCustomerID,
		&i.Timezone,
		&i.EmailVerified,
		&i.GoogleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, sleep_baseline, estimated_score, calendar_connected, calendar_token, calendar_synced_at, tier, paddle_customer_id, timezone, email_verified, google_id, deleted_at, created_at, updated_at FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.SleepBaseline,
		&i.EstimatedScore,
		&i.CalendarConnected,
		&i.CalendarToken,
		&i.CalendarSyncedAt,
		&i.Tier,
		&i.PaddleCustomerID,
		&i.Timezone,
		&i.EmailVerified,
		&i.GoogleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, password_hash, name, role, sleep_baseline, estimated_score, calendar_connected, calendar_token, calendar_synced_at, tier, paddle_customer_id, timezone, email_verified, google_id, deleted_at, created_at, updated_at FROM users
WHERE google_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.SleepBaseline,
		&i.EstimatedScore,
		&i.CalendarConnected,
		&i.CalendarToken,
		&i.CalendarSyncedAt,
		&i.Tier,
		&i.PaddleCustomerID,
		&i.Timezone,
		&i.EmailVerified,
		&i.GoogleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, sleep_baseline, estimated_score, calendar_connected, calendar_token, calendar_synced_at, tier, paddle_customer_id, timezone, email_verified, google_id, deleted_at, created_at, updated_at FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.SleepBaseline,
		&i.EstimatedScore,
		&i.CalendarConnected,
		&i.CalendarToken,
		&i.CalendarSyncedAt,
		&i.Tier,
		&i.PaddleCustomerID,
		&i.Timezone,
		&i.EmailVerified,
		&i.GoogleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPaddleCustomerID = `-- name: GetUserByPaddleCustomerID :one
SELECT id, email, password_hash, name, role, sleep_baseline, estimated_score, calendar_connected, calendar_token, calendar_synced_at, tier, paddle_customer_id, timezone, email_verified, google_id, deleted_at, created_at, updated_at FROM users
WHERE paddle_customer_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByPaddleCustomerID(ctx context.Context, paddleCustomerID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPaddleCustomerID, paddleCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.SleepBaseline,
		&i.EstimatedScore,
		&i.CalendarConnected,
		&i.CalendarToken,
		&i.CalendarSyncedAt,
		&i.Tier,
		&i.PaddleCustomerID,
		&i.Timezone,
		&i.EmailVerified,
		&i.GoogleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersForCheckinReminder = `-- name: ListUsersForCheckinReminder :many
SELECT
    u.id,
    u.email,
    u.name,
    u.timezone,
    np.reminder_time
FROM users u
JOIN user_notification_prefs np ON np.user_id = u.id
WHERE u.deleted_at IS NULL
  AND u.email_verified = TRUE
  AND np.checkin_reminder = TRUE
  -- match current UTC minute against user's local time
  AND TO_CHAR(
        (NOW() AT TIME ZONE u.timezone)::TIME,
        'HH24:MI'
      ) = TO_CHAR(np.reminder_time, 'HH24:MI')
  -- no check-in today in user's local date
  AND NOT EXISTS (
      SELECT 1 FROM check_ins ci
      WHERE ci.user_id = u.id
        AND ci.checked_in_date = (NOW() AT TIME ZONE u.timezone)::DATE
  )
`

type ListUsersForCheckinReminderRow struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Email        string      `db:"email" json:"email"`
	Name         string      `db:"name" json:"name"`
	Timezone     string      `db:"timezone" json:"timezone"`
	ReminderTime pgtype.Time `db:"reminder_time" json:"reminder_time"`
}

// Called by the cron job every minute; returns users whose local time
// matches their reminder_time and who have not yet checked in today.
func (q *Queries) ListUsersForCheckinReminder(ctx context.Context) ([]ListUsersForCheckinReminderRow, error) {
	rows, err := q.db.Query(ctx, listUsersForCheckinReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForCheckinReminderRow{}
	for rows.Next() {
		var i ListUsersForCheckinReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Timezone,
			&i.ReminderTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForMondayDebrief = `-- name: ListUsersForMondayDebrief :many
SELECT u.id, u.email, u.name, u.timezone
FROM users u
JOIN user_notification_prefs np ON np.user_id = u.id
WHERE u.deleted_at IS NULL
  AND u.email_verified = TRUE
  AND np.monday_debrief_email = TRUE
  AND EXTRACT(DOW  FROM (NOW() AT TIME ZONE u.timezone)) = 1
  AND EXTRACT(HOUR FROM (NOW() AT TIME ZONE u.timezone)) BETWEEN 7 AND 9
  AND (
      SELECT COUNT(*) FROM check_ins ci
      WHERE ci.user_id = u.id
        AND ci.checked_in_date >= (NOW() AT TIME ZONE u.timezone)::DATE - 7
  ) >= 3
  AND NOT EXISTS (
      SELECT 1 FROM email_logs el
      WHERE el.user_id = u.id
        AND el.template = 'monday-debrief'
        AND el.dedup_key = 'monday-debrief-' || TO_CHAR(NOW() AT TIME ZONE u.timezone, 'IYYY-IW')
        AND el.status = 'sent'
  )
`

type ListUsersForMondayDebriefRow struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Email    string    `db:"email" json:"email"`
	Name     string    `db:"name" json:"name"`
	Timezone string    `db:"timezone" json:"timezone"`
}

// Users for whom it's Monday morning (local time 7–10 AM) and who have
// ≥3 check-ins in the past 7 days and haven't received this week's debrief.
func (q *Queries) ListUsersForMondayDebrief(ctx context.Context) ([]ListUsersForMondayDebriefRow, error) {
	rows, err := q.db.Query(ctx, listUsersForMondayDebrief)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForMondayDebriefRow{}
	for rows.Next() {
		var i ListUsersForMondayDebriefRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForReengagement = `-- name: ListUsersForReengagement :many
SELECT DISTINCT u.id, u.email, u.name
FROM users u
JOIN user_notification_prefs np ON np.user_id = u.id
WHERE u.deleted_at IS NULL
  AND u.email_verified = TRUE
  AND np.re_engage_email = TRUE
  AND NOT EXISTS (
      SELECT 1 FROM check_ins ci
      WHERE ci.user_id = u.id
        AND ci.checked_in_date >= CURRENT_DATE - 2
  )
  AND (
      SELECT COUNT(*) FROM check_ins ci
      WHERE ci.user_id = u.id
        AND ci.checked_in_date >= CURRENT_DATE - 14
  ) >= 5
  AND NOT EXISTS (
      SELECT 1 FROM email_logs el
      WHERE el.user_id = u.id
        AND el.template = 're-engage'
        AND el.status = 'sent'
        AND el.sent_at >= NOW() - INTERVAL '7 days'
  )
`

type ListUsersForReengagementRow struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Email string    `db:"email" json:"email"`
	Name  string    `db:"name" json:"name"`
}

// Users who have ≥5 check-ins in the last 14 days but none in the past 2 days,
// and haven't received a re-engagement email in the last 7 days.
func (q *Queries) ListUsersForReengagement(ctx context.Context) ([]ListUsersForReengagementRow, error) {
	rows, err := q.db.Query(ctx, listUsersForReengagement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForReengagementRow{}
	for rows.Next() {
		var i ListUsersForReengagementRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForStreakAlert = `-- name: ListUsersForStreakAlert :many
SELECT u.id, u.email, u.name, u.timezone
FROM users u
JOIN user_notification_prefs np ON np.user_id = u.id
WHERE u.deleted_at IS NULL
  AND u.email_verified = TRUE
  AND np.streak_alert_email = TRUE
  AND EXTRACT(HOUR FROM (NOW() AT TIME ZONE u.timezone)) >= 18
  AND NOT EXISTS (
      SELECT 1 FROM check_ins ci
      WHERE ci.user_id = u.id
        AND ci.checked_in_date = (NOW() AT TIME ZONE u.timezone)::DATE
  )
  AND NOT EXISTS (
      SELECT 1 FROM email_logs el
      WHERE el.user_id = u.id
        AND el.template = 'streak-alert'
        AND el.dedup_key = 'streak-alert-' || TO_CHAR(NOW() AT TIME ZONE u.timezone, 'YYYY-MM-DD')
        AND el.status = 'sent'
  )
`

type ListUsersForStreakAlertRow struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Email    string    `db:"email" json:"email"`
	Name     string    `db:"name" json:"name"`
	Timezone string    `db:"timezone" json:"timezone"`
}

// Users with a streak ≥5 who haven't checked in today and whose local
// time is past 6 PM — sent once per day.
func (q *Queries) ListUsersForStreakAlert(ctx context.Context) ([]ListUsersForStreakAlertRow, error) {
	rows, err := q.db.Query(ctx, listUsersForStreakAlert)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForStreakAlertRow{}
	for rows.Next() {
		var i ListUsersForStreakAlertRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCalendarToken = `-- name: SetCalendarToken :exec
UPDATE users SET
    calendar_token      = $2,
    calendar_connected  = TRUE,
    calendar_synced_at  = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type SetCalendarTokenParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	CalendarToken []byte    `db:"calendar_token" json:"calendar_token"`
}

func (q *Queries) SetCalendarToken(ctx context.Context, arg SetCalendarTokenParams) error {
	_, err := q.db.Exec(ctx, setCalendarToken, arg.ID, arg.CalendarToken)
	return err
}

const setEstimatedScore = `-- name: SetEstimatedScore :exec
UPDATE users SET
    estimated_score = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SetEstimatedScoreParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	EstimatedScore pgtype.Int2 `db:"estimated_score" json:"estimated_score"`
}

func (q *Queries) SetEstimatedScore(ctx context.Context, arg SetEstimatedScoreParams) error {
	_, err := q.db.Exec(ctx, setEstimatedScore, arg.ID, arg.EstimatedScore)
	return err
}

const setPaddleCustomerID = `-- name: SetPaddleCustomerID :exec
UPDATE users SET
    paddle_customer_id = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SetPaddleCustomerIDParams struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	PaddleCustomerID pgtype.Text `db:"paddle_customer_id" json:"paddle_customer_id"`
}

func (q *Queries) SetPaddleCustomerID(ctx context.Context, arg SetPaddleCustomerIDParams) error {
	_, err := q.db.Exec(ctx, setPaddleCustomerID, arg.ID, arg.PaddleCustomerID)
	return err
}

const setUserGoogleID = `-- name: SetUserGoogleID :exec
UPDATE users SET
    google_id = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SetUserGoogleIDParams struct {
	ID       uuid.UUID   `db:"id" json:"id"`
	GoogleID pgtype.Text `db:"google_id" json:"google_id"`
}

func (q *Queries) SetUserGoogleID(ctx context.Context, arg SetUserGoogleIDParams) error {
	_, err := q.db.Exec(ctx, setUserGoogleID, arg.ID, arg.GoogleID)
	return err
}

const setUserTier = `-- name: SetUserTier :exec
UPDATE users SET
    tier = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SetUserTierParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Tier string    `db:"tier" json:"tier"`
}

func (q *Queries) SetUserTier(ctx context.Context, arg SetUserTierParams) error {
	_, err := q.db.Exec(ctx, setUserTier, arg.ID, arg.Tier)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET
    deleted_at = NOW(),
    email      = email || '.deleted.' || EXTRACT(EPOCH FROM NOW())::BIGINT
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateCalendarSyncedAt = `-- name: UpdateCalendarSyncedAt :exec
UPDATE users SET
    calendar_synced_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UpdateCalendarSyncedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateCalendarSyncedAt, id)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users SET
    email          = $2,
    email_verified = FALSE
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, email, password_hash, name, role, sleep_baseline, estimated_score, calendar_connected, calendar_token, calendar_synced_at, tier, paddle_customer_id, timezone, email_verified, google_id, deleted_at, created_at, updated_at
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Email string    `db:"email" json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.SleepBaseline,
		&i.EstimatedScore,
		&i.CalendarConnected,
		&i.CalendarToken,
		&i.CalendarSyncedAt,
		&i.Tier,
		&i.PaddleCustomerID,
		&i.Timezone,
		&i.EmailVerified,
		&i.GoogleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET
    password_hash = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    name            = COALESCE($2,           name),
    role            = COALESCE($3,           role),
    sleep_baseline  = COALESCE($4, sleep_baseline),
    timezone        = COALESCE($5,       timezone)
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, email, password_hash, name, role, sleep_baseline, estimated_score, calendar_connected, calendar_token, calendar_synced_at, tier, paddle_customer_id, timezone, email_verified, google_id, deleted_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Name          pgtype.Text `db:"name" json:"name"`
	Role          pgtype.Text `db:"role" json:"role"`
	SleepBaseline pgtype.Int2 `db:"sleep_baseline" json:"sleep_baseline"`
	Timezone      pgtype.Text `db:"timezone" json:"timezone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.SleepBaseline,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.SleepBaseline,
		&i.EstimatedScore,
		&i.CalendarConnected,
		&i.CalendarToken,
		&i.CalendarSyncedAt,
		&i.Tier,
		&i.PaddleCustomerID,
		&i.Timezone,
		&i.EmailVerified,
		&i.GoogleID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET
    email_verified = TRUE
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
